"""add fields 'about_me', 'last_seen' in User model

Revision ID: 58564ae8f354
Revises: ddd0dfad4513
Create Date: 2025-01-28 14:49:34.435760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58564ae8f354'
down_revision = 'ddd0dfad4513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
